#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


EXPECTED_TARGET = {
    "vendor_id": "0x10de",
    "device_id": "0x2f04",
    "iopcimatch": "0x2f0410de",
    "subsystem_vendor_id": "0x1458",
    "subsystem_id": "0x417e",
}


REQUIRED_FALSE_FLAGS = [
    "pci_config_writes",
    "mmio_writes",
    "bar_poking",
    "gpu_reset",
    "firmware_loading",
    "gsp_initialization",
    "display_engine_init",
    "framebuffer_init",
    "metal_acceleration_attempt",
    "driverkit_activation",
]


def load_summary(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        raise SystemExit(f"Summary JSON not found: {path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {path}: {exc}")

    if not isinstance(data, dict):
        raise SystemExit(f"Summary JSON must contain an object: {path}")

    return data


def normalize(value: Any) -> str:
    return str(value).strip().lower()


def check_summary(data: dict[str, Any]) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []

    def add(name: str, passed: bool, detail: str) -> None:
        checks.append(
            {
                "name": name,
                "passed": passed,
                "detail": detail,
            }
        )

    schema = data.get("schema", "")
    add(
        "schema",
        schema == "h1mekartx.bar_inventory_summary.v1",
        f"schema={schema!r}",
    )

    target = data.get("target", {})
    if not isinstance(target, dict):
        target = {}

    for key, expected in EXPECTED_TARGET.items():
        actual = normalize(target.get(key, ""))
        add(
            f"target.{key}",
            actual == expected,
            f"expected={expected}, actual={actual or '<missing>'}",
        )

    safety = data.get("safety_boundary", {})
    if not isinstance(safety, dict):
        safety = {}

    add(
        "safety_boundary.read_only",
        safety.get("read_only") is True,
        f"actual={safety.get('read_only')!r}",
    )

    for flag in REQUIRED_FALSE_FLAGS:
        add(
            f"safety_boundary.{flag}",
            safety.get(flag) is False,
            f"actual={safety.get(flag)!r}",
        )

    target_hits = data.get("target_hits", {})
    if not isinstance(target_hits, dict):
        target_hits = {}

    add(
        "target_hits.vendor_10de",
        int(target_hits.get("vendor_10de", 0) or 0) >= 1,
        f"actual={target_hits.get('vendor_10de', 0)!r}",
    )

    add(
        "target_hits.device_or_iopcimatch",
        (
            int(target_hits.get("device_2f04", 0) or 0) >= 1
            or int(target_hits.get("iopcimatch_2f0410de", 0) or 0) >= 1
        ),
        (
            f"device_2f04={target_hits.get('device_2f04', 0)!r}, "
            f"iopcimatch_2f0410de={target_hits.get('iopcimatch_2f0410de', 0)!r}"
        ),
    )

    return checks


def markdown_report(summary_path: Path, checks: list[dict[str, Any]]) -> str:
    passed_count = sum(1 for item in checks if item["passed"])
    failed_count = len(checks) - passed_count
    overall = "PASS" if failed_count == 0 else "FAIL"

    rows = []
    for item in checks:
        status = "PASS" if item["passed"] else "FAIL"
        rows.append(f"| {item['name']} | {status} | `{item['detail']}` |")

    return "\n".join(
        [
            "# BAR/MMIO Safety Boundary Check",
            "",
            f"Generated UTC: `{datetime.now(timezone.utc).isoformat()}`",
            "",
            f"Input summary: `{summary_path}`",
            "",
            f"Overall: `{overall}`",
            "",
            f"Passed: `{passed_count}`",
            "",
            f"Failed: `{failed_count}`",
            "",
            "## Checks",
            "",
            "| Check | Status | Detail |",
            "| --- | --- | --- |",
            *rows,
            "",
            "## Safety Boundary",
            "",
            "This checker validates the Stage 4 summary metadata only.",
            "",
            "It does not perform PCI config-space writes, MMIO writes, BAR poking, GPU reset logic, GSP initialization, firmware loading, display engine initialization, framebuffer initialization, Metal acceleration attempts, or DriverKit activation.",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate the H1mekaRTX BAR/MMIO safety boundary from a Stage 4 summary JSON."
    )
    parser.add_argument(
        "summary_json",
        help="Path to bar-inventory-summary.json generated by scripts/summarize-bar-inventory.py",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Optional output directory for bar-mmio-safety-check.md",
    )

    args = parser.parse_args()

    summary_path = Path(args.summary_json).expanduser().resolve()
    data = load_summary(summary_path)
    checks = check_summary(data)

    failed = [item for item in checks if not item["passed"]]

    for item in checks:
        status = "PASS" if item["passed"] else "FAIL"
        print(f"{status}: {item['name']} - {item['detail']}")

    if args.out_dir:
        out_dir = Path(args.out_dir).expanduser().resolve()
        out_dir.mkdir(parents=True, exist_ok=True)
        report_path = out_dir / "bar-mmio-safety-check.md"
        report_path.write_text(markdown_report(summary_path, checks) + "\n")
        print(f"Wrote: {report_path}")

    if failed:
        print(f"Safety boundary check failed: {len(failed)} issue(s)")
        return 1

    print("Safety boundary check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
