#!/usr/bin/env bash
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$HOME/Desktop/H1mekaRTX-phase1-diagnostics-$(date +%Y%m%d-%H%M%S)}"

HOST_DIR="$OUT/host-diagnostics-raw"
BAR_DIR="$OUT/bar-inventory-raw"
UI_SAMPLE_DIR="$OUT/ui-compositor-sample-raw"
UI_ATTRIBUTION_DIR="$OUT/ui-gpu-attribution-raw"
BUNDLE_DIR="$OUT/host-report-bundle"

mkdir -p "$OUT"

echo "== H1mekaRTX Phase 1 diagnostics bundle =="
echo "Repo: $ROOT"
echo "Out:  $OUT"

echo
echo "== Collect host + UI compositor diagnostics =="
"$ROOT/scripts/collect-host-diagnostics.sh" "$HOST_DIR"

echo
echo "== Summarize host + UI compositor diagnostics =="
python3 "$ROOT/scripts/summarize-host-diagnostics.py" --input-dir "$HOST_DIR" --out-dir "$OUT"

echo
echo "== Collect BAR inventory diagnostics =="
"$ROOT/scripts/collect-bar-inventory.sh" "$BAR_DIR"

echo
echo "== Summarize BAR inventory diagnostics =="
python3 "$ROOT/scripts/summarize-bar-inventory.py" "$BAR_DIR" --out-dir "$OUT"

echo
echo "== Generate UI compositor proof schema =="
python3 "$ROOT/scripts/generate-ui-compositor-proof-schema.py" --out-dir "$OUT"

echo
echo "== Collect baseline UI compositor sample diagnostics =="
H1MEKARTX_UI_SAMPLE_LABEL="${H1MEKARTX_UI_SAMPLE_LABEL:-phase1-baseline-ui-sample}" \
H1MEKARTX_UI_SAMPLE_LAST="${H1MEKARTX_UI_SAMPLE_LAST:-5m}" \
"$ROOT/scripts/collect-ui-compositor-sample.sh" "$UI_SAMPLE_DIR"

echo
echo "== Summarize baseline UI compositor sample diagnostics =="
python3 "$ROOT/scripts/summarize-ui-compositor-sample.py" --input-dir "$UI_SAMPLE_DIR" --out-dir "$OUT"

echo
echo "== Collect UI GPU attribution diagnostics =="
H1MEKARTX_UI_ATTRIBUTION_LAST="${H1MEKARTX_UI_ATTRIBUTION_LAST:-10m}" \
"$ROOT/scripts/collect-ui-gpu-attribution.sh" "$UI_ATTRIBUTION_DIR"

echo
echo "== Summarize UI GPU attribution diagnostics =="
python3 "$ROOT/scripts/summarize-ui-gpu-attribution.py" --input-dir "$UI_ATTRIBUTION_DIR" --out-dir "$OUT"

echo
echo "== Generate UI workload correlation report =="
python3 "$ROOT/scripts/generate-ui-workload-correlation-report.py" \
  --host-summary "$OUT/host-diagnostics-summary.json" \
  --ui-sample-summary "$OUT/ui-compositor-sample-summary.json" \
  --ui-gpu-attribution-summary "$OUT/ui-gpu-attribution-summary.json" \
  --out-dir "$OUT"

echo
echo "== Generate UI compositor readiness matrix =="
python3 "$ROOT/scripts/generate-ui-compositor-readiness-matrix.py" \
  --host-summary "$OUT/host-diagnostics-summary.json" \
  --ui-sample-summary "$OUT/ui-compositor-sample-summary.json" \
  --ui-gpu-attribution-summary "$OUT/ui-gpu-attribution-summary.json" \
  --ui-workload-correlation-report "$OUT/ui-workload-correlation-report.json" \
  --proof-schema "$OUT/ui-compositor-proof-schema.json" \
  --out-dir "$OUT"

echo
echo "== Generate Metal acceleration entry gate =="
python3 "$ROOT/scripts/generate-metal-acceleration-entry-gate.py" \
  --host-summary "$OUT/host-diagnostics-summary.json" \
  --bar-inventory-summary "$OUT/bar-inventory-summary.json" \
  --ui-compositor-readiness-matrix "$OUT/ui-compositor-readiness-matrix.json" \
  --ui-workload-correlation-report "$OUT/ui-workload-correlation-report.json" \
  --out-dir "$OUT"

echo
echo "== Create local host report bundle =="
python3 "$ROOT/scripts/create-local-host-report-bundle.py" --input-dir "$OUT" --bundle-dir "$BUNDLE_DIR"

echo
echo "== Create local diagnostics index =="
python3 "$ROOT/scripts/generate-local-diagnostics-index.py" --root "$OUT" --out-dir "$OUT"

cat > "$OUT/README.md" <<EOF
# H1mekaRTX Phase 1 Diagnostics Bundle

Generated by:

    scripts/create-phase1-diagnostics-bundle.sh

## Primary Reports

- host-diagnostics-summary.json
- host-diagnostics-summary.md
- bar-inventory-summary.json
- bar-inventory-summary.md
- ui-compositor-proof-schema.json
- ui-compositor-proof-schema.md
- ui-compositor-sample-summary.json
- ui-compositor-sample-summary.md
- ui-gpu-attribution-summary.json
- ui-gpu-attribution-summary.md
- ui-workload-correlation-report.json
- ui-workload-correlation-report.md
- ui-compositor-readiness-matrix.json
- ui-compositor-readiness-matrix.md
- metal-acceleration-entry-gate.json
- metal-acceleration-entry-gate.md
- local-diagnostics-index.json
- local-diagnostics-index.md
- host-report-bundle/bundle.json
- host-report-bundle/README.md

## Raw Captures

- host-diagnostics-raw/
- bar-inventory-raw/
- ui-compositor-sample-raw/
- ui-gpu-attribution-raw/

## Classification

- Host diagnostics: collected.
- Graphics stack diagnostics: collected.
- Runtime probe: not attempted.
- Real GPU command execution: not attempted.
- UI compositor proof: unproven.
- Metal proof: unproven.
- Real RTX 5070 Metal acceleration implementation: blocked.

## Safety Boundary

This runner performs read-only macOS diagnostics collection and local report generation.

No DriverKit activation.

No System Extension activation.

No device ownership request.

No PCI config-space writes.

No MMIO reads.

No MMIO writes.

No BAR mapping.

No BAR poking.

No GPU command submission.

No RTX 5070 UI compositor acceleration claim.

No RTX 5070 Metal acceleration claim.
EOF

echo
echo "Wrote: $OUT"
echo "Open:  $OUT/README.md"
