#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


BUNDLE_SCHEMA = "h1mekartx.host_report_bundle.v1"

TARGET = {
    "gpu": "NVIDIA RTX 5070",
    "vendorID": "0x10de",
    "deviceID": "0x2f04",
    "iopcimatch": "0x2f0410de",
    "subsystemVendorID": "0x1458",
    "subsystemID": "0x417e",
}

REPORT_CANDIDATES = [
    {
        "source": "metal-workload-runtime.json",
        "dest": "reports/metal-workload-runtime.json",
        "kind": "local_report",
        "required": False,
        "description": "Optional public Metal workload runtime JSON saved by the user.",
    },
    {
        "source": "metal-workload-result-schema.json",
        "dest": "reports/metal-workload-result-schema.json",
        "kind": "local_report",
        "required": False,
        "description": "Optional generated Metal workload result schema.",
    },
    {
        "source": "metal-workload-regression-manifest.json",
        "dest": "reports/metal-workload-regression-manifest.json",
        "kind": "local_report",
        "required": False,
        "description": "Optional generated Metal workload regression manifest.",
    },
    {
        "source": "host-status.json",
        "dest": "reports/host-status.json",
        "kind": "local_report",
        "required": False,
        "description": "Optional no-activation host status JSON saved by the user.",
    },
    {
        "source": "host-diagnostics-summary.json",
        "dest": "reports/host-diagnostics-summary.json",
        "kind": "host_diagnostics",
        "required": False,
        "description": "Optional Phase 1 host and graphics stack diagnostics JSON summary.",
    },
    {
        "source": "host-diagnostics-summary.md",
        "dest": "reports/host-diagnostics-summary.md",
        "kind": "host_diagnostics",
        "required": False,
        "description": "Optional Phase 1 host and graphics stack diagnostics Markdown summary.",
    },
    {
        "source": "rendered-host-status-report.md",
        "dest": "reports/rendered-host-status-report.md",
        "kind": "local_report",
        "required": False,
        "description": "Optional local rendered host status Markdown.",
    },
    {
        "source": "forbidden-bar-operation-audit.md",
        "dest": "reports/safety-gates.md",
        "kind": "local_report",
        "required": False,
        "description": "Optional safety gate Markdown copied from a local generated report.",
    },
]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_if_present(input_dir: Path, bundle_dir: Path, item: dict[str, Any]) -> dict[str, Any]:
    source = input_dir / item["source"]
    dest = bundle_dir / item["dest"]

    record = {
        "path": item["dest"],
        "sourcePath": str(source),
        "kind": item["kind"],
        "required": item["required"],
        "present": False,
        "sha256": None,
        "bytes": 0,
        "description": item["description"],
    }

    if not source.exists() or not source.is_file():
        return record

    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, dest)

    record["present"] = True
    record["sha256"] = sha256_file(dest)
    record["bytes"] = dest.stat().st_size
    return record


def write_readme(bundle_dir: Path, manifest: dict[str, Any]) -> None:
    report_lines = []
    for item in manifest["reports"]:
        status = "present" if item["present"] else "missing"
        report_lines.append(
            f"| `{item['path']}` | `{status}` | `{item['kind']}` | `{item['bytes']}` |"
        )

    text = "\n".join(
        [
            "# H1mekaRTX Local Host Report Bundle",
            "",
            f"Generated UTC: `{manifest['generatedAtUTC']}`",
            "",
            f"Decision: `{manifest['bundleDecision']}`",
            "",
            f"Bundle type: `{manifest['bundleType']}`",
            "",
            "## Target",
            "",
            f"- GPU: `{manifest['target']['gpu']}`",
            f"- Vendor ID: `{manifest['target']['vendorID']}`",
            f"- Device ID: `{manifest['target']['deviceID']}`",
            f"- IOPCIMatch: `{manifest['target']['iopcimatch']}`",
            f"- Subsystem Vendor ID: `{manifest['target']['subsystemVendorID']}`",
            f"- Subsystem ID: `{manifest['target']['subsystemID']}`",
            "",
            "## Reports",
            "",
            "| Path | Status | Kind | Bytes |",
            "| --- | --- | --- | ---: |",
            *report_lines,
            "",
            "## Safety Boundary",
            "",
            "This bundle is local-file-only.",
            "",
            "It was generated by copying already-existing local reports into a bundle folder and writing local summary metadata.",
            "",
            "It does not query live extension state, submit extension requests, activate DriverKit, request device ownership, collect live PCI inventory, access PCI configuration space, access MMIO, map BAR memory, execute RTX 5070 shaders, submit hardware commands, allocate RTX 5070 resources, load firmware, initialize display paths, initialize framebuffer, or reset the GPU.",
            "",
        ]
    )

    (bundle_dir / "README.md").write_text(text + "\n")


def build_bundle(input_dir: Path, bundle_dir: Path) -> dict[str, Any]:
    if bundle_dir.exists():
        shutil.rmtree(bundle_dir)

    bundle_dir.mkdir(parents=True, exist_ok=True)

    reports = [copy_if_present(input_dir, bundle_dir, item) for item in REPORT_CANDIDATES]
    present_count = sum(1 for item in reports if item["present"])

    manifest = {
        "schema": BUNDLE_SCHEMA,
        "generatedAtUTC": datetime.now(timezone.utc).isoformat(),
        "target": TARGET,
        "bundleDecision": "LOCAL_HOST_REPORT_BUNDLE_CREATED",
        "bundleType": "LOCAL_ONLY_REPORT_BUNDLE",
        "inputDirectory": str(input_dir),
        "bundleDirectory": str(bundle_dir),
        "reportCount": len(reports),
        "presentReportCount": present_count,
        "reports": reports,
        "safetyBoundary": {
            "localFilesOnly": True,
            "copiesExistingLocalReportsOnly": True,
            "noLiveExtensionQuery": True,
            "noSystemExtensionRequests": True,
            "noDriverKitActivation": True,
            "noDeviceOwnershipRequest": True,
            "noPCIConfigAccess": True,
            "noMMIOAccess": True,
            "noBARMapping": True,
            "noRTX5070Acceleration": True,
            "noRTX5070ShaderExecution": True,
            "noHardwareCommandSubmission": True,
            "noRTX5070ResourceAllocation": True,
            "noFirmwareLoading": True,
            "noDisplayInitialization": True,
            "noFramebufferInitialization": True,
            "noGPUReset": True,
        },
    }

    (bundle_dir / "bundle.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    write_readme(bundle_dir, manifest)

    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a local-only H1mekaRTX host report bundle from existing local reports."
    )
    parser.add_argument(
        "--input-dir",
        default=".",
        help="Directory containing already-generated local reports. Defaults to current directory.",
    )
    parser.add_argument(
        "--bundle-dir",
        default="host-report-bundle",
        help="Bundle output directory. Defaults to host-report-bundle.",
    )

    args = parser.parse_args()

    input_dir = Path(args.input_dir).expanduser().resolve()
    bundle_dir = Path(args.bundle_dir).expanduser().resolve()

    if not input_dir.exists() or not input_dir.is_dir():
        raise SystemExit(f"Input directory does not exist: {input_dir}")

    manifest = build_bundle(input_dir, bundle_dir)

    print(f"Wrote: {bundle_dir / 'bundle.json'}")
    print(f"Wrote: {bundle_dir / 'README.md'}")
    print(f"Decision: {manifest['bundleDecision']}")
    print(f"Present reports: {manifest['presentReportCount']}/{manifest['reportCount']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
