#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCHEMA = "h1mekartx.bar_evidence_ledger.v1"

TARGET = {
    "gpu": "NVIDIA RTX 5070",
    "vendor_id": "0x10de",
    "device_id": "0x2f04",
    "iopcimatch": "0x2f0410de",
    "subsystem_vendor_id": "0x1458",
    "subsystem_id": "0x417e",
}

BAR_SLOTS = ["BAR0", "BAR1", "BAR2", "BAR3", "BAR4", "BAR5", "ROM"]

EVIDENCE_CLASSES = [
    {
        "class": "OS_VISIBLE_INVENTORY",
        "allowed": True,
        "description": "Existing Stage 3/4 inventory text or normalized summaries already collected before this stage.",
    },
    {
        "class": "REPO_DOCUMENTATION",
        "allowed": True,
        "description": "Repository markdown and JSON generated by earlier safe stages.",
    },
    {
        "class": "PUBLIC_VENDOR_INDEPENDENT_PCI_DOCS",
        "allowed": True,
        "description": "General PCI concepts only; no target-specific live probing.",
    },
    {
        "class": "LIVE_PCI_PROBING",
        "allowed": False,
        "description": "Disallowed. This stage does not run ioreg, system_profiler, or config-space reads.",
    },
    {
        "class": "LIVE_BAR_MAPPING",
        "allowed": False,
        "description": "Disallowed. This stage does not map BAR memory or access MMIO.",
    },
    {
        "class": "WRITE_BASED_SIZE_PROBING",
        "allowed": False,
        "description": "Disallowed. This stage does not write PCI config registers.",
    },
]

SOURCE_CANDIDATES = [
    "docs/metal/bar-inventory-diagnostics.md",
    "docs/metal/bar-inventory-report-normalizer.md",
    "docs/metal/bar-mmio-risk-ledger.md",
    "docs/metal/bar-access-readiness-matrix.md",
    "docs/metal/bar-access-policy-default-deny.md",
    "docs/metal/forbidden-bar-operation-audit.md",
    "docs/metal/bar-role-research-plan.md",
    "docs/metal/command-memory-model-placeholders.md",
    "docs/metal/metal-implementation-decision-gate.md",
    "docs/metal/implementation-blocker-register.md",
]

FORBIDDEN_NOW = [
    "live PCI probing",
    "ioreg collection",
    "system_profiler collection",
    "PCI config-space reads",
    "PCI config-space writes",
    "MMIO reads",
    "MMIO writes",
    "BAR memory mapping",
    "BAR memory poking",
    "BAR size probing by writes",
    "register offset probing",
    "DriverKit activation",
    "IOPCIDevice ownership request",
    "RTX 5070 Metal acceleration implementation",
    "RTX 5070 shader execution",
    "hardware command submission",
    "queue or ring programming",
    "doorbell interaction",
    "RTX 5070 resource allocation",
    "firmware loading",
    "GSP initialization",
    "display engine initialization",
    "framebuffer initialization",
    "GPU reset logic",
]


def read_text(path: Path) -> str:
    try:
        return path.read_text(errors="replace")
    except FileNotFoundError:
        return ""


def classify_repo_sources(root: Path) -> list[dict[str, Any]]:
    sources: list[dict[str, Any]] = []

    for rel in SOURCE_CANDIDATES:
        path = root / rel
        text = read_text(path)
        lower = text.lower()

        sources.append(
            {
                "path": rel,
                "present": path.exists(),
                "bytes": path.stat().st_size if path.exists() else 0,
                "mentions_bar": "bar" in lower,
                "mentions_mmio": "mmio" in lower,
                "mentions_iopcidevice": "iopcidevice" in lower,
                "mentions_metal": "metal" in lower,
                "evidence_class": "REPO_DOCUMENTATION",
                "allowed": True,
            }
        )

    return sources


def inspect_optional_inventory_dir(inventory_dir: Path | None) -> dict[str, Any]:
    if inventory_dir is None:
        return {
            "provided": False,
            "path": None,
            "present": False,
            "files": [],
            "target_hints": {},
        }

    files: list[dict[str, Any]] = []
    combined = ""

    if inventory_dir.exists() and inventory_dir.is_dir():
        for path in sorted(inventory_dir.glob("*")):
            if path.is_file() and path.suffix.lower() in {".txt", ".md", ".json"}:
                text = read_text(path)
                combined += "\n" + text[:200000]
                files.append(
                    {
                        "name": path.name,
                        "bytes": path.stat().st_size,
                        "mentions_target_vendor": "10de" in text.lower(),
                        "mentions_target_device": "2f04" in text.lower(),
                        "mentions_iopcimatch": "2f0410de" in text.lower(),
                        "mentions_assigned_addresses": "assigned-addresses" in text.lower(),
                        "mentions_reg": bool(re.search(r'\breg\b', text.lower())),
                    }
                )

    lower = combined.lower()

    return {
        "provided": True,
        "path": str(inventory_dir),
        "present": inventory_dir.exists() and inventory_dir.is_dir(),
        "files": files,
        "target_hints": {
            "vendor_10de": lower.count("10de"),
            "device_2f04": lower.count("2f04"),
            "iopcimatch_2f0410de": lower.count("2f0410de"),
            "assigned_addresses": lower.count("assigned-addresses"),
            "reg": len(re.findall(r'\breg\b', lower)),
            "bar_token": lower.count("bar"),
            "rom_token": lower.count("rom"),
        },
    }


def build_bar_entries(optional_inventory: dict[str, Any]) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []

    target_hint_count = sum(optional_inventory.get("target_hints", {}).values()) if optional_inventory.get("target_hints") else 0
    has_optional_inventory = optional_inventory.get("present") is True and target_hint_count > 0

    for slot in BAR_SLOTS:
        if has_optional_inventory:
            evidence_state = "INVENTORY_HINTS_PRESENT_ROLE_UNVERIFIED"
            confidence = "LOW"
            evidence_summary = "Optional existing inventory directory contains target/BAR-adjacent hints, but no slot role is verified."
        else:
            evidence_state = "NO_SLOT_SPECIFIC_EVIDENCE"
            confidence = "NONE"
            evidence_summary = "No slot-specific non-invasive evidence was provided to this ledger."

        entries.append(
            {
                "slot": slot,
                "current_role": "UNKNOWN",
                "confidence": confidence,
                "evidence_state": evidence_state,
                "evidence_summary": evidence_summary,
                "allowed_evidence_classes": [
                    "OS_VISIBLE_INVENTORY",
                    "REPO_DOCUMENTATION",
                    "PUBLIC_VENDOR_INDEPENDENT_PCI_DOCS",
                ],
                "forbidden_evidence_classes": [
                    "LIVE_PCI_PROBING",
                    "LIVE_BAR_MAPPING",
                    "WRITE_BASED_SIZE_PROBING",
                ],
                "role_assignment_allowed": False,
                "bar_access_allowed": False,
                "next_action": "Keep role UNKNOWN until non-invasive slot-specific evidence exists.",
            }
        )

    return entries


def build_ledger(root: Path, inventory_dir: Path | None) -> dict[str, Any]:
    repo_sources = classify_repo_sources(root)
    optional_inventory = inspect_optional_inventory_dir(inventory_dir)
    bar_entries = build_bar_entries(optional_inventory)

    source_present_count = sum(1 for item in repo_sources if item["present"])
    roles_unknown_count = sum(1 for item in bar_entries if item["current_role"] == "UNKNOWN")

    return {
        "schema": SCHEMA,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "repo_root": str(root),
        "target": TARGET,
        "decision": "BAR_EVIDENCE_LEDGER_READY_ROLES_STILL_UNKNOWN",
        "full_metal_goal": True,
        "research_continues": True,
        "implementation_allowed": False,
        "implementation_started": False,
        "bar_access_allowed": False,
        "role_assignment_allowed": False,
        "repo_source_present_count": source_present_count,
        "bar_slot_count": len(bar_entries),
        "roles_unknown_count": roles_unknown_count,
        "evidence_classes": EVIDENCE_CLASSES,
        "repo_sources": repo_sources,
        "optional_inventory": optional_inventory,
        "bar_entries": bar_entries,
        "forbidden_now": FORBIDDEN_NOW,
        "next_stage_recommendation": "Stage 25 should expand public Metal reference workloads on the existing system Metal device only.",
        "safety_boundary": {
            "read_only": True,
            "documentation_only": True,
            "uses_existing_artifacts_only": True,
            "runs_ioreg": False,
            "runs_system_profiler": False,
            "performs_pci_config_reads": False,
            "performs_pci_config_writes": False,
            "performs_mmio_reads": False,
            "performs_mmio_writes": False,
            "maps_bar_memory": False,
            "bar_poking": False,
            "bar_size_probing": False,
            "register_offset_probing": False,
            "driverkit_activation": False,
            "iopcidevice_ownership_request": False,
            "rtx5070_metal_acceleration_implementation": False,
            "rtx5070_shader_execution": False,
            "hardware_command_submission": False,
            "resource_allocation_on_rtx5070": False,
            "firmware_loading": False,
            "gsp_initialization": False,
            "display_engine_init": False,
            "framebuffer_init": False,
            "gpu_reset": False,
        },
    }


def markdown_report(data: dict[str, Any]) -> str:
    evidence_rows = []
    for item in data["evidence_classes"]:
        evidence_rows.append(
            f"| `{item['class']}` | `{item['allowed']}` | {item['description']} |"
        )

    source_rows = []
    for item in data["repo_sources"]:
        source_rows.append(
            f"| `{item['path']}` | `{item['present']}` | {item['bytes']} | `{item['mentions_bar']}` | `{item['mentions_mmio']}` | `{item['mentions_iopcidevice']}` | `{item['mentions_metal']}` |"
        )

    bar_rows = []
    for item in data["bar_entries"]:
        bar_rows.append(
            f"| `{item['slot']}` | `{item['current_role']}` | `{item['confidence']}` | `{item['evidence_state']}` | {item['evidence_summary']} | `{item['role_assignment_allowed']}` | `{item['bar_access_allowed']}` | {item['next_action']} |"
        )

    forbidden_lines = [f"- {item}" for item in data["forbidden_now"]]

    return "\n".join(
        [
            "# BAR Evidence Ledger",
            "",
            f"Generated UTC: `{data['generated_at_utc']}`",
            "",
            f"Decision: `{data['decision']}`",
            "",
            f"Full Metal goal: `{data['full_metal_goal']}`",
            "",
            f"Research continues: `{data['research_continues']}`",
            "",
            f"Implementation allowed: `{data['implementation_allowed']}`",
            "",
            f"Implementation started: `{data['implementation_started']}`",
            "",
            f"BAR access allowed: `{data['bar_access_allowed']}`",
            "",
            f"Role assignment allowed: `{data['role_assignment_allowed']}`",
            "",
            f"Repo source present count: `{data['repo_source_present_count']}`",
            "",
            f"BAR slot count: `{data['bar_slot_count']}`",
            "",
            f"Roles unknown count: `{data['roles_unknown_count']}`",
            "",
            "## Target",
            "",
            f"- GPU: `{data['target']['gpu']}`",
            f"- Vendor ID: `{data['target']['vendor_id']}`",
            f"- Device ID: `{data['target']['device_id']}`",
            f"- IOPCIMatch: `{data['target']['iopcimatch']}`",
            f"- Subsystem Vendor ID: `{data['target']['subsystem_vendor_id']}`",
            f"- Subsystem ID: `{data['target']['subsystem_id']}`",
            "",
            "## Evidence Classes",
            "",
            "| Class | Allowed | Description |",
            "| --- | --- | --- |",
            *evidence_rows,
            "",
            "## Repository Sources",
            "",
            "| Path | Present | Bytes | Mentions BAR | Mentions MMIO | Mentions IOPCIDevice | Mentions Metal |",
            "| --- | ---: | ---: | --- | --- | --- | --- |",
            *source_rows,
            "",
            "## BAR Entries",
            "",
            "| Slot | Current Role | Confidence | Evidence State | Evidence Summary | Role Assignment Allowed | BAR Access Allowed | Next Action |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
            *bar_rows,
            "",
            "## Optional Inventory Directory",
            "",
            f"- Provided: `{data['optional_inventory']['provided']}`",
            f"- Present: `{data['optional_inventory']['present']}`",
            f"- Path: `{data['optional_inventory']['path']}`",
            "",
            "## Forbidden Now",
            "",
            *forbidden_lines,
            "",
            "## Safety Boundary",
            "",
            "This ledger is documentation-only and uses existing artifacts only.",
            "",
            "It does not run ioreg, run system_profiler, perform PCI config-space reads, perform PCI config-space writes, perform MMIO reads, perform MMIO writes, map BAR memory, poke BAR memory, probe BAR sizes, probe register offsets, activate DriverKit, request IOPCIDevice ownership, start RTX 5070 Metal acceleration implementation, execute RTX 5070 shaders, submit hardware commands, allocate RTX 5070 resources, load firmware, initialize GSP, initialize display engine, initialize framebuffer, or run GPU reset logic.",
            "",
            "## Next Stage",
            "",
            data["next_stage_recommendation"],
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate H1mekaRTX BAR evidence ledger from existing artifacts only."
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Repository root. Defaults to current directory.",
    )
    parser.add_argument(
        "--inventory-dir",
        default=None,
        help="Optional existing Stage 3/4 inventory directory to read. This script never collects live inventory.",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory. Defaults to repo root.",
    )

    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    inventory_dir = Path(args.inventory_dir).expanduser().resolve() if args.inventory_dir else None
    out_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else root

    if not root.exists() or not root.is_dir():
        raise SystemExit(f"Repository root does not exist: {root}")

    out_dir.mkdir(parents=True, exist_ok=True)

    data = build_ledger(root, inventory_dir)

    json_path = out_dir / "bar-evidence-ledger.json"
    md_path = out_dir / "bar-evidence-ledger.md"

    json_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    md_path.write_text(markdown_report(data) + "\n")

    print(f"Wrote: {json_path}")
    print(f"Wrote: {md_path}")
    print(f"Decision: {data['decision']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
