#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCHEMA = "h1mekartx.host_report_bundle_format.v1"

TARGET = {
    "gpu": "NVIDIA RTX 5070",
    "vendor_id": "0x10de",
    "device_id": "0x2f04",
    "iopcimatch": "0x2f0410de",
    "subsystem_vendor_id": "0x1458",
    "subsystem_id": "0x417e",
}

BUNDLE_LAYOUT = [
    {
        "path": "bundle.json",
        "required": True,
        "kind": "manifest",
        "description": "Top-level bundle manifest with schema, target identity, included report list, and safety boundary.",
    },
    {
        "path": "README.md",
        "required": True,
        "kind": "human_summary",
        "description": "Human-readable local bundle summary.",
    },
    {
        "path": "reports/metal-workload-runtime.json",
        "required": False,
        "kind": "local_report",
        "description": "Optional runtime JSON from the public Metal workload suite.",
    },
    {
        "path": "reports/metal-workload-result-schema.json",
        "required": False,
        "kind": "local_report",
        "description": "Optional generated workload result schema.",
    },
    {
        "path": "reports/metal-workload-regression-manifest.json",
        "required": False,
        "kind": "local_report",
        "description": "Optional generated regression manifest.",
    },
    {
        "path": "reports/host-status.json",
        "required": False,
        "kind": "local_report",
        "description": "Optional no-activation host status JSON.",
    },
    {
        "path": "reports/host-diagnostics-summary.json",
        "required": False,
        "kind": "host_diagnostics",
        "description": "Optional Phase 1 host and graphics stack diagnostics JSON summary.",
    },
    {
        "path": "reports/host-diagnostics-summary.md",
        "required": False,
        "kind": "host_diagnostics",
        "description": "Optional Phase 1 host and graphics stack diagnostics Markdown summary.",
    },
    {
        "path": "reports/rendered-host-status-report.md",
        "required": False,
        "kind": "local_report",
        "description": "Optional local rendered host status markdown.",
    },
    {
        "path": "reports/safety-gates.md",
        "required": False,
        "kind": "local_report",
        "description": "Optional safety gate output copied by the user.",
    },
]

BUNDLE_MANIFEST_SCHEMA = {
    "schema": "h1mekartx.host_report_bundle.v1",
    "required_top_level_fields": [
        "schema",
        "generatedAtUTC",
        "target",
        "bundleDecision",
        "bundleType",
        "reports",
        "safetyBoundary",
    ],
    "report_fields": [
        "path",
        "kind",
        "required",
        "present",
        "sha256",
        "bytes",
    ],
    "safety_boundary_fields": [
        "localFilesOnly",
        "noLiveExtensionQuery",
        "noSystemExtensionRequests",
        "noDriverKitActivation",
        "noDeviceOwnershipRequest",
        "noPCIConfigAccess",
        "noMMIOAccess",
        "noBARMapping",
        "noRTX5070Acceleration",
        "noHardwareCommandSubmission",
    ],
}

ALLOWED_INPUTS = [
    "existing local JSON reports generated by repository scripts",
    "existing local Markdown reports generated by repository scripts",
    "optional Swift host no-activation JSON output saved by the user",
    "optional public Metal workload runtime JSON saved by the user",
]

FORBIDDEN_INPUTS = [
    "live extension state query",
    "automatic log collection",
    "live PCI probing",
    "ioreg collection",
    "system_profiler collection",
    "PCI config-space access",
    "MMIO access",
    "BAR mapping",
    "DriverKit activation result",
    "RTX 5070 command submission result",
]

FORBIDDEN_NOW = [
    "host GUI implementation",
    "DriverKit dext target creation",
    "System Extension activation request",
    "System Extension deactivation request",
    "extension manager submit request",
    "DriverKit activation",
    "device ownership request",
    "live extension status query",
    "live PCI probing",
    "ioreg collection",
    "system_profiler collection",
    "PCI config-space reads",
    "PCI config-space writes",
    "MMIO reads",
    "MMIO writes",
    "BAR memory mapping",
    "BAR memory poking",
    "RTX 5070 Metal acceleration implementation",
    "RTX 5070 shader execution",
    "hardware command submission to RTX 5070",
    "RTX 5070 resource allocation",
    "firmware loading",
    "GSP initialization",
    "display engine initialization",
    "framebuffer initialization",
    "GPU reset logic",
]


def build_format() -> dict[str, Any]:
    return {
        "schema": SCHEMA,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "target": TARGET,
        "decision": "HOST_REPORT_BUNDLE_FORMAT_READY",
        "full_metal_goal": True,
        "research_continues": True,
        "host_side_tooling_started": True,
        "real_acceleration_production_started": False,
        "real_acceleration_production_allowed": False,
        "bundle_type": "LOCAL_ONLY_REPORT_BUNDLE",
        "bundle_layout": BUNDLE_LAYOUT,
        "bundle_manifest_schema": BUNDLE_MANIFEST_SCHEMA,
        "allowed_inputs": ALLOWED_INPUTS,
        "forbidden_inputs": FORBIDDEN_INPUTS,
        "forbidden_now": FORBIDDEN_NOW,
        "next_stage_recommendation": "Stage 38 should add a local host report bundle generator that copies existing local reports into the bundle format without live queries or hardware access.",
        "safety_boundary": {
            "read_only": True,
            "documentation_only": True,
            "format_only": True,
            "local_files_only": True,
            "host_gui_implementation": False,
            "live_extension_status_query": False,
            "system_extension_activation_request": False,
            "system_extension_deactivation_request": False,
            "extension_manager_submit_request": False,
            "driverkit_activation": False,
            "device_ownership_request": False,
            "rtx5070_metal_acceleration_attempt": False,
            "rtx5070_shader_execution": False,
            "hardware_command_submission_to_rtx5070": False,
            "resource_allocation_on_rtx5070": False,
            "live_pci_probing": False,
            "runs_ioreg": False,
            "runs_system_profiler": False,
            "performs_pci_config_reads": False,
            "performs_pci_config_writes": False,
            "performs_mmio_reads": False,
            "performs_mmio_writes": False,
            "maps_bar_memory": False,
            "bar_poking": False,
            "firmware_loading": False,
            "gsp_initialization": False,
            "display_engine_init": False,
            "framebuffer_init": False,
            "gpu_reset": False,
        },
    }


def markdown_report(data: dict[str, Any]) -> str:
    layout_rows = []
    for item in data["bundle_layout"]:
        layout_rows.append(
            f"| `{item['path']}` | `{item['required']}` | `{item['kind']}` | {item['description']} |"
        )

    manifest_rows = []
    for key, value in data["bundle_manifest_schema"].items():
        if isinstance(value, list):
            fields = ", ".join(f"`{x}`" for x in value)
        else:
            fields = f"`{value}`"
        manifest_rows.append(f"| `{key}` | {fields} |")

    allowed_lines = [f"- {item}" for item in data["allowed_inputs"]]
    forbidden_input_lines = [f"- {item}" for item in data["forbidden_inputs"]]
    forbidden_lines = [f"- {item}" for item in data["forbidden_now"]]

    return "\n".join(
        [
            "# Host Report Bundle Format",
            "",
            f"Generated UTC: `{data['generated_at_utc']}`",
            "",
            f"Decision: `{data['decision']}`",
            "",
            f"Full Metal goal: `{data['full_metal_goal']}`",
            "",
            f"Research continues: `{data['research_continues']}`",
            "",
            f"Host-side tooling started: `{data['host_side_tooling_started']}`",
            "",
            f"Real acceleration production started: `{data['real_acceleration_production_started']}`",
            "",
            f"Real acceleration production allowed: `{data['real_acceleration_production_allowed']}`",
            "",
            f"Bundle type: `{data['bundle_type']}`",
            "",
            "## Target",
            "",
            f"- GPU: `{data['target']['gpu']}`",
            f"- Vendor ID: `{data['target']['vendor_id']}`",
            f"- Device ID: `{data['target']['device_id']}`",
            f"- IOPCIMatch: `{data['target']['iopcimatch']}`",
            f"- Subsystem Vendor ID: `{data['target']['subsystem_vendor_id']}`",
            f"- Subsystem ID: `{data['target']['subsystem_id']}`",
            "",
            "## Bundle Layout",
            "",
            "| Path | Required | Kind | Description |",
            "| --- | --- | --- | --- |",
            *layout_rows,
            "",
            "## Bundle Manifest Schema",
            "",
            "| Area | Fields |",
            "| --- | --- |",
            *manifest_rows,
            "",
            "## Allowed Inputs",
            "",
            *allowed_lines,
            "",
            "## Forbidden Inputs",
            "",
            *forbidden_input_lines,
            "",
            "## Forbidden Now",
            "",
            *forbidden_lines,
            "",
            "## Safety Boundary",
            "",
            "This stage is format-only and documentation-only.",
            "",
            "It defines a local report bundle format only. It does not query live extension status, submit extension requests, activate DriverKit, request device ownership, collect live PCI inventory, access PCI configuration space, access MMIO, map BAR memory, execute RTX 5070 shaders, submit hardware commands, allocate RTX 5070 resources, load firmware, initialize display paths, or reset the GPU.",
            "",
            "## Next Stage",
            "",
            data["next_stage_recommendation"],
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate H1mekaRTX host report bundle format.")
    parser.add_argument("--out-dir", default=".", help="Output directory. Defaults to current directory.")
    args = parser.parse_args()

    out_dir = Path(args.out_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    data = build_format()

    json_path = out_dir / "host-report-bundle-format.json"
    md_path = out_dir / "host-report-bundle-format.md"

    json_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    md_path.write_text(markdown_report(data) + "\n")

    print(f"Wrote: {json_path}")
    print(f"Wrote: {md_path}")
    print(f"Decision: {data['decision']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
